import assert from 'node:assert/strict';
import {registrarCaixaDiario,resumirCaixaDiario,pagarDespesaNoCaixa,excluirCaixaDiario,registrarDevedor,listarDevedores,baixarDevedor} from '../src/js/backend/core/escolar.js';

const caixa=[],devedores=[],lancamentos=[],auditoria=[];let n=0;
const db={proximoId:p=>`${p}-${++n}`,listarCaixaDiario:()=>[...caixa],listarLancamentos:()=>[...lancamentos],listarDevedores:()=>[...devedores],executar:async(q,p)=>{if(q.startsWith('INSERT INTO lancamentos'))lancamentos.push({id:p[0],descricao:p[1],tipo:p[2],valorCentavos:p[5],competencia:p[6],situacao:p[9],liquidadoEm:p[8],vencimento:p[7]});else if(q.startsWith('UPDATE lancamentos SET situacao=')){const id=p.length===5?p[4]:p[3],item=lancamentos.find(x=>x.id===id);item.situacao=p[0];if(p.length===5){item.competencia=p[1];item.liquidadoEm=p[2];item.atualizadoEm=p[3]}else{item.liquidadoEm=p[1];item.atualizadoEm=p[2]}}else if(q.startsWith('DELETE FROM lancamentos')){const i=lancamentos.findIndex(x=>x.id===p[0]);if(i>=0)lancamentos.splice(i,1)}else if(q.startsWith('INSERT INTO caixa_diario')){const novo=p.length===13;caixa.push({id:p[0],data:p[1],competencia:novo?p[2]:'',tipo:novo?p[3]:p[2],origem:novo?p[4]:p[3],aluno:novo?p[5]:p[4],responsavel:novo?p[6]:p[5],formaPagamento:novo?p[7]:p[6],valorCentavos:novo?p[8]:p[7],observacao:novo?p[9]:p[8],lancamentoId:novo?p[10]:p[9],criadoEm:novo?p[11]:p[10],usuarioId:novo?p[12]:p[11]})}else if(q.startsWith('DELETE FROM caixa_diario')){const i=caixa.findIndex(x=>x.id===p[0]);if(i>=0)caixa.splice(i,1)}else if(q.startsWith('INSERT INTO alunos_devedores'))devedores.push({id:p[0],aluno:p[1],turma:p[2],responsavel:p[3],contato:p[4],descricao:p[5],valorCentavos:p[6],valorPagoCentavos:0,vencimento:p[7],situacao:p[8],observacao:p[9],criadoEm:p[10],atualizadoEm:p[11],usuarioId:p[12]});else if(q.startsWith('UPDATE alunos_devedores SET situacao=')){const item=devedores.find(x=>x.id===p[3]);item.situacao=p[0];item.valorPagoCentavos=p[1];item.atualizadoEm=p[2]}else if(q.startsWith('INSERT INTO auditoria'))auditoria.push(p)}};

assert.equal((await registrarCaixaDiario(db,{data:'2026-08-27',receitasCentavos:35000,despesasCentavos:8000,mesReferencia:'2026-07'})).ok,true);
assert.equal(lancamentos.length,2);
assert.equal(resumirCaixaDiario(db,{data:'2026-08-27'}).receitas,35000);
assert.equal(resumirCaixaDiario(db,{data:'2026-08-27'}).despesas,8000);
assert.equal(lancamentos.find(x=>x.tipo==='despesa').competencia,'2026-07-27');
lancamentos.push({id:'despesa-fixa',tipo:'despesa',descricao:'Energia elétrica',valorCentavos:12500,competencia:'2026-07-15',vencimento:'2026-09-20',situacao:'pendente',liquidadoEm:null});
assert.equal((await pagarDespesaNoCaixa(db,{id:'despesa-fixa',data:'2026-08-27',mesReferencia:'2026-06'})).ok,true);
assert.equal(lancamentos.find(x=>x.id==='despesa-fixa').situacao,'pago');
assert.equal(lancamentos.find(x=>x.id==='despesa-fixa').competencia,'2026-06-15');
assert.equal(caixa.some(x=>x.lancamentoId==='despesa-fixa'&&x.formaPagamento==='Dinheiro'),true);
assert.equal(caixa.find(x=>x.lancamentoId==='despesa-fixa').competencia,'2026-06-15');
assert.equal((await pagarDespesaNoCaixa(db,{id:'despesa-fixa',data:'2026-08-27'})).ok,false);
const caixaAgregado=caixa.find(x=>x.origem==='Fechamento diário'&&x.tipo==='despesa'),caixaCadastrado=caixa.find(x=>x.lancamentoId==='despesa-fixa');
assert.equal((await excluirCaixaDiario(db,caixaAgregado.id)).ok,true);
assert.equal(caixa.some(x=>x.id===caixaAgregado.id),false);
assert.equal((await excluirCaixaDiario(db,caixaCadastrado.id)).ok,true);
assert.equal(lancamentos.find(x=>x.id==='despesa-fixa').situacao,'pendente');
const cadastroDevedor=await registrarDevedor(db,{aluno:'Bruno CELC',descricao:'Mensalidade agosto',valorCentavos:42000,vencimento:'2026-08-30'});
assert.equal(cadastroDevedor.ok,true);
assert.equal(listarDevedores(db,{situacao:'em_aberto'}).length,1);
assert.equal((await baixarDevedor(db,cadastroDevedor.devedor.id,{data:'2026-08-27',valorCentavos:12000})).situacao,'parcial');
assert.equal(listarDevedores(db,{situacao:'parcial'}).length,1);
assert.equal((await baixarDevedor(db,cadastroDevedor.devedor.id,{data:'2026-08-27',valorCentavos:30000})).situacao,'quitado');
assert.equal(listarDevedores(db,{situacao:'quitado'}).length,1);
assert.equal(auditoria.length>=4,true);
assert.equal((await registrarCaixaDiario(db,{data:'2026-08-27',despesasCentavos:100,mesReferencia:'2026-13'})).ok,false);
console.log('21 asserções aprovadas — caixa escolar, competência mensal, despesas, exclusão e pagamentos parciais de alunos.');
