const TIPOS=new Set(['entrada','despesa']);const SITUACOES=new Set(['previsto','pendente','pago','recebido','vencido']);const liquidado=x=>x.tipo==='entrada'?x.situacao==='recebido':x.situacao==='pago';const agora=()=>new Date().toISOString();
function situacaoGerida(d,atual=null){if(typeof d.liquidado==='boolean')return d.tipo==='entrada'?(d.liquidado?'recebido':'previsto'):(d.liquidado?'pago':'pendente');return atual?.situacao||String(d.situacao||'');}
function validar(d,atual=null){const descricao=String(d.descricao||'').trim(),tipo=String(d.tipo||''),categoria=String(d.categoria||'').trim(),valorCentavos=Number(d.valorCentavos),competencia=String(d.competencia||''),situacao=situacaoGerida(d,atual);if(!descricao)return {erro:'Informe a descrição do lançamento.'};if(!TIPOS.has(tipo))return {erro:'Selecione entrada ou despesa.'};if(!categoria)return {erro:'Selecione uma categoria.'};if(!Number.isSafeInteger(valorCentavos)||valorCentavos<=0)return {erro:'Informe um valor maior que zero.'};if(!/^\d{4}-\d{2}-\d{2}$/.test(competencia))return {erro:'Informe uma data válida.'};if(!SITUACOES.has(situacao))return {erro:'Informe se o pagamento foi realizado.'};return {descricao,tipo,categoria,valorCentavos,competencia,situacao};}
async function auditar(db,u,acao,id){await db.executar('INSERT INTO auditoria (usuario_id,acao,entidade,entidade_id,criado_em,detalhes) VALUES (?,?,?,?,?,?)',[u.id,acao,'lancamento',id,agora(),'']);}
export async function salvarLancamento(db,dados,u={id:'direcao-celc'}){const v=validar(dados);if(v.erro)return {ok:false,erro:v.erro};const id=db.proximoId('lanc'),t=agora(),item={id,...v,categoriaId:dados.categoriaId||null,vencimento:dados.vencimento||null,recorrencia:dados.recorrencia==='mensal'?'mensal':'avulso',criadoEm:t,atualizadoEm:t,usuarioId:u.id};await db.executar('INSERT INTO lancamentos (id,descricao,tipo,categoria_id,categoria,valor_centavos,competencia,vencimento,liquidado_em,situacao,recorrencia,criado_em,atualizado_em,usuario_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[item.id,item.descricao,item.tipo,item.categoriaId,item.categoria,item.valorCentavos,item.competencia,item.vencimento,liquidado(item)?t:null,item.situacao,item.recorrencia,item.criadoEm,item.atualizadoEm,item.usuarioId]);await auditar(db,u,'criar',id);return {ok:true,lancamento:item};}
export async function editarLancamento(db,id,dados,u={id:'direcao-celc'}){const atual=db.listarLancamentos().find(x=>x.id===id);if(!atual)return {ok:false,erro:'Lançamento não encontrado.'};const v=validar({...atual,...dados},atual);if(v.erro)return {ok:false,erro:v.erro};const t=agora(),liquidadoAgora=liquidado({tipo:v.tipo,situacao:v.situacao});await db.executar('UPDATE lancamentos SET descricao=?,tipo=?,categoria_id=?,categoria=?,valor_centavos=?,competencia=?,vencimento=?,situacao=?,recorrencia=?,atualizado_em=? WHERE id=?',[v.descricao,v.tipo,dados.categoriaId||atual.categoriaId,v.categoria,v.valorCentavos,v.competencia,dados.vencimento||null,v.situacao,dados.recorrencia==='mensal'?'mensal':'avulso',t,id]);if(liquidadoAgora&&!atual.liquidadoEm)await db.executar('UPDATE lancamentos SET situacao=?,liquidado_em=?,atualizado_em=? WHERE id=?',[v.situacao,t,t,id]);await auditar(db,u,'editar',id);return {ok:true};}
export async function baixarLancamento(db,id,u={id:'direcao-celc'}){const item=db.listarLancamentos().find(x=>x.id===id);if(!item)return {ok:false,erro:'Lançamento não encontrado.'};if(liquidado(item))return {ok:false,erro:'Este lançamento já foi liquidado.'};const situacao=item.tipo==='entrada'?'recebido':'pago',t=agora();await db.executar('UPDATE lancamentos SET situacao=?,liquidado_em=?,atualizado_em=? WHERE id=?',[situacao,t,t,id]);await auditar(db,u,'baixar',id);return {ok:true,situacao};}
export async function atualizarLancamentosVencidos(db,{referencia=new Date().toISOString().slice(0,10)}={},u={id:'direcao-celc'}){if(!/^\d{4}-\d{2}-\d{2}$/.test(referencia))return {ok:false,erro:'Informe uma data de referência válida.'};const t=agora(),vencidos=[];for(const item of db.listarLancamentos()){if(liquidado(item)||!item.vencimento||item.vencimento>=referencia||item.situacao==='vencido')continue;await db.executar('UPDATE lancamentos SET situacao=?,atualizado_em=? WHERE id=?',['vencido',t,item.id]);await auditar(db,u,'vencer',item.id);vencidos.push(item.id);}return {ok:true,quantidade:vencidos.length,ids:vencidos};}
export async function excluirLancamento(db,id,u={id:'direcao-celc'}){const item=db.listarLancamentos().find(x=>x.id===id);if(!item)return {ok:false,erro:'Lançamento não encontrado.'};await db.executar('DELETE FROM lancamentos WHERE id=?',[id]);await auditar(db,u,'excluir',id);return {ok:true};}
export function resumirLancamentos(db,ref){const mes=ref.slice(0,7),todos=db.listarLancamentos(),doMes=todos.filter(x=>x.competencia.startsWith(mes)),realizados=doMes.filter(liquidado),somar=t=>realizados.filter(x=>x.tipo===t).reduce((s,x)=>s+x.valorCentavos,0),entradas=somar('entrada'),despesas=somar('despesa'),saldoDisponivel=todos.filter(liquidado).reduce((s,x)=>s+(x.tipo==='entrada'?x.valorCentavos:-x.valorCentavos),0),previsto=doMes.filter(x=>!liquidado(x)).reduce((s,x)=>s+(x.tipo==='entrada'?x.valorCentavos:-x.valorCentavos),0);return {saldoDisponivel,entradas,despesas,resultado:entradas-despesas,previsto,projecao:saldoDisponivel+previsto,recentes:todos,doMes};}
export function consultarLancamentos(db,{tipo='',situacoes=[],inicio='',fim='',busca=''}={}){return db.listarLancamentos().filter(x=>(!tipo||x.tipo===tipo)&&(!situacoes.length||situacoes.includes(x.situacao))&&(!inicio||x.competencia>=inicio)&&(!fim||x.competencia<=fim)&&(!busca||`${x.descricao} ${x.categoria}`.toLowerCase().includes(busca.toLowerCase())));}
export async function gerarRecorrenciasMensais(db,ref,u={id:'direcao-celc'}){const alvo=ref.slice(0,7),modelos=db.listarLancamentos().filter(x=>x.recorrencia==='mensal'&&x.competencia.slice(0,7)<alvo),criados=[];for(const m of modelos){if(db.listarLancamentos().some(x=>x.competencia.startsWith(alvo)&&x.descricao===m.descricao&&x.categoria===m.categoria&&x.tipo===m.tipo))continue;const dia=(m.vencimento||m.competencia).slice(8,10),r=await salvarLancamento(db,{...m,competencia:`${alvo}-${dia}`,vencimento:m.vencimento?`${alvo}-${dia}`:'',situacao:m.tipo==='entrada'?'previsto':'pendente'},u);if(r.ok)criados.push(r.lancamento)}return criados;}
