export function gerarCsvLancamentos(lancamentos) {
  const esc = (valor) => `"${String(valor).replaceAll('"', '""')}"`;
  const linhas = [['Data', 'Descrição', 'Tipo', 'Categoria', 'Situação', 'Recorrência', 'Valor']];
  lancamentos.forEach((item) => linhas.push([item.competencia, item.descricao, item.tipo, item.categoria, item.situacao, item.recorrencia, (item.valorCentavos / 100).toFixed(2).replace('.', ',')]));
  return `\uFEFF${linhas.map((linha) => linha.map(esc).join(';')).join('\r\n')}`;
}

const liquidado=item=>item.tipo==='entrada'?item.situacao==='recebido':item.situacao==='pago';
const dentroDoPeriodo=(item,inicio,fim)=>item.competencia>=inicio&&item.competencia<=fim;
const somar=itens=>itens.reduce((total,item)=>total+item.valorCentavos,0);
function agruparPorCategoria(itens,tipo){const grupos=new Map();itens.filter(item=>item.tipo===tipo).forEach(item=>{const atual=grupos.get(item.categoria)||{categoria:item.categoria,realizado:0,projetado:0,pendente:0,quantidade:0};atual.quantidade+=1;atual.projetado+=item.valorCentavos;if(liquidado(item))atual.realizado+=item.valorCentavos;else atual.pendente+=item.valorCentavos;grupos.set(item.categoria,atual)});return [...grupos.values()].sort((a,b)=>b.projetado-a.projetado||a.categoria.localeCompare(b.categoria));}
export function resumirRelatorios(db,{inicio='',fim=''}={}){const hoje=new Date().toISOString().slice(0,10),inicioPadrao=inicio||`${hoje.slice(0,7)}-01`,fimPadrao=fim||hoje,periodo=db.listarLancamentos().filter(item=>dentroDoPeriodo(item,inicioPadrao,fimPadrao)),realizados=periodo.filter(liquidado),entradasRealizadas=somar(realizados.filter(item=>item.tipo==='entrada')),despesasRealizadas=somar(realizados.filter(item=>item.tipo==='despesa')),aReceber=somar(periodo.filter(item=>item.tipo==='entrada'&&!liquidado(item))),aPagar=somar(periodo.filter(item=>item.tipo==='despesa'&&!liquidado(item))),entradasProjetadas=entradasRealizadas+aReceber,despesasProjetadas=despesasRealizadas+aPagar,categoriasEntrada=agruparPorCategoria(periodo,'entrada'),categoriasDespesa=agruparPorCategoria(periodo,'despesa'),fluxo=[...realizados].sort((a,b)=>`${a.liquidadoEm||a.competencia}${a.id}`.localeCompare(`${b.liquidadoEm||b.competencia}${b.id}`)).map(item=>({data:(item.liquidadoEm||item.competencia).slice(0,10),descricao:item.descricao,categoria:item.categoria,tipo:item.tipo,valorCentavos:item.valorCentavos})),devedores=db.listarDevedores?db.listarDevedores():[],emAberto=devedores.filter(item=>item.situacao!=='quitado').map(item=>({...item,saldoCentavos:Math.max(0,item.valorCentavos-Number(item.valorPagoCentavos||0))})),inadimplentes=emAberto.filter(item=>item.vencimento<hoje),dividaEmAberto=emAberto.reduce((total,item)=>total+item.saldoCentavos,0),dividaVencida=inadimplentes.reduce((total,item)=>total+item.saldoCentavos,0);return {inicio:inicioPadrao,fim:fimPadrao,totais:{entradasRealizadas,despesasRealizadas,resultadoRealizado:entradasRealizadas-despesasRealizadas,aReceber,aPagar,entradasProjetadas,despesasProjetadas,resultadoProjetado:entradasProjetadas-despesasProjetadas},categoriasEntrada,categoriasDespesa,fluxo,devedores:{quantidade:emAberto.length,valor:dividaEmAberto,vencidos:inadimplentes.length,valorVencido:dividaVencida,itens:emAberto.sort((a,b)=>a.vencimento.localeCompare(b.vencimento))}};}

const moeda=valor=>`R$ ${(valor/100).toFixed(2).replace('.',',')}`;
const dataBr=data=>data?data.split('-').reverse().join('/'):'-';
const cp1252=texto=>{const bytes=[];for(const caractere of String(texto)){let codigo=caractere.codePointAt(0);if(codigo>255){const simples=caractere.normalize('NFD').replace(/[\u0300-\u036f]/g,'');codigo=simples.codePointAt(0)||63;}bytes.push(codigo<=255?codigo:63);}return new Uint8Array(bytes);};
const juntar=partes=>{const tamanho=partes.reduce((total,parte)=>total+parte.length,0),saida=new Uint8Array(tamanho);let inicio=0;partes.forEach(parte=>{saida.set(parte,inicio);inicio+=parte.length;});return saida;};
const textoPdf=texto=>String(texto).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
function gerarPdf(linhas){const porPagina=[];for(let i=0;i<linhas.length;i+=43)porPagina.push(linhas.slice(i,i+43));const objetos=[];const idsPaginas=[];objetos[1]=cp1252('<< /Type /Catalog /Pages 2 0 R >>');objetos[3]=cp1252('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');objetos[4]=cp1252('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');porPagina.forEach((pagina,indice)=>{const paginaId=5+indice*2,conteudoId=paginaId+1;idsPaginas.push(`${paginaId} 0 R`);let y=800;const comandos=pagina.map(linha=>{const fonte=linha.negrito?'F2':'F1',tamanho=linha.tamanho||10,comando=`BT /${fonte} ${tamanho} Tf 48 ${y} Td (${textoPdf(linha.texto)}) Tj ET\n`;y-=linha.altura||15;return comando;}).join('');const conteudo=cp1252(comandos);objetos[paginaId]=cp1252(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${conteudoId} 0 R >>`);objetos[conteudoId]=juntar([cp1252(`<< /Length ${conteudo.length} >>\nstream\n`),conteudo,cp1252('\nendstream')]);});objetos[2]=cp1252(`<< /Type /Pages /Kids [${idsPaginas.join(' ')}] /Count ${idsPaginas.length} >>`);let corpo=cp1252('%PDF-1.4\n%CELC\n'),offsets=[0];for(let id=1;id<objetos.length;id+=1){offsets[id]=corpo.length;corpo=juntar([corpo,cp1252(`${id} 0 obj\n`),objetos[id],cp1252('\nendobj\n')]);}const inicioXref=corpo.length;let xref=`xref\n0 ${objetos.length}\n0000000000 65535 f \n`;for(let id=1;id<objetos.length;id+=1)xref+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;return juntar([corpo,cp1252(`${xref}trailer\n<< /Size ${objetos.length} /Root 1 0 R >>\nstartxref\n${inicioXref}\n%%EOF`)]);}
export function gerarPdfRelatorio(relatorio){const t=relatorio.totais,linhas=[{texto:'CELC Financeiro - Relatório gerencial',negrito:true,tamanho:18,altura:28},{texto:`Período: ${dataBr(relatorio.inicio)} a ${dataBr(relatorio.fim)}`,tamanho:10,altura:24},{texto:'Resumo financeiro',negrito:true,tamanho:13,altura:19},{texto:`Entradas realizadas: ${moeda(t.entradasRealizadas)}`},{texto:`Despesas realizadas: ${moeda(t.despesasRealizadas)}`},{texto:`Resultado realizado: ${moeda(t.resultadoRealizado)}`},{texto:`A receber: ${moeda(t.aReceber)} | A pagar: ${moeda(t.aPagar)}`},{texto:`Resultado projetado: ${moeda(t.resultadoProjetado)}`,negrito:true,altura:22},{texto:'Entradas por categoria',negrito:true,tamanho:13,altura:19},...relatorio.categoriasEntrada.map(item=>({texto:`${item.categoria}: realizado ${moeda(item.realizado)} | a receber ${moeda(item.pendente)} | projetado ${moeda(item.projetado)}`})),{texto:'Despesas por categoria',negrito:true,tamanho:13,altura:19},...relatorio.categoriasDespesa.map(item=>({texto:`${item.categoria}: pago ${moeda(item.realizado)} | a pagar ${moeda(item.pendente)} | projetado ${moeda(item.projetado)}`})),{texto:'Inadimplência',negrito:true,tamanho:13,altura:19},{texto:`Em aberto: ${relatorio.devedores.quantidade} aluno(s) - ${moeda(relatorio.devedores.valor)}`},{texto:`Vencidos: ${relatorio.devedores.vencidos} aluno(s) - ${moeda(relatorio.devedores.valorVencido)}`},{texto:'Fluxo de caixa realizado',negrito:true,tamanho:13,altura:19},...relatorio.fluxo.map(item=>({texto:`${dataBr(item.data)} | ${item.tipo==='entrada'?'Entrada':'Despesa'} | ${item.categoria} | ${item.descricao} | ${moeda(item.valorCentavos)}`}))];return gerarPdf(linhas);}

export async function exportarRelatorio(Neutralino, banco,{inicio='',fim=''}={}) {
  if (!Neutralino || banco.modo !== 'sqlite') return { ok: false, erro: 'A exportação está disponível no executável Windows.' };
  const pasta = `${banco.caminho.slice(0, banco.caminho.lastIndexOf('\\'))}\\exportacoes`;
  try { await Neutralino.filesystem.createDirectory(pasta); } catch { /* pasta existente */ }
  const caminho = `${pasta}\\fluxo-de-caixa-${new Date().toISOString().slice(0, 10)}.csv`;
  const itens=banco.listarLancamentos().filter(item=>(!inicio||item.competencia>=inicio)&&(!fim||item.competencia<=fim));
  await Neutralino.filesystem.writeFile(caminho, gerarCsvLancamentos(itens));
  return { ok: true, caminho };
}

export async function exportarRelatorioPdf(Neutralino,banco,filtros={}){if(!Neutralino||banco.modo!=='sqlite')return {ok:false,erro:'A exportação está disponível no executável Windows.'};const pasta=`${banco.caminho.slice(0,banco.caminho.lastIndexOf('\\'))}\\exportacoes`;try{await Neutralino.filesystem.createDirectory(pasta)}catch{}const caminho=`${pasta}\\relatorio-financeiro-${new Date().toISOString().slice(0,10)}.pdf`,bytes=gerarPdfRelatorio(resumirRelatorios(banco,filtros));await Neutralino.filesystem.writeBinaryFile(caminho,bytes);return {ok:true,caminho};}
